/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AssistantRouteImport } from './routes/assistant';
import { Route as AuditRouteImport } from './routes/audit';
import { Route as IncidentsRouteImport } from './routes/incidents';
import { Route as KnowledgeRouteImport } from './routes/knowledge';
import { Route as LockRouteImport } from './routes/lock';
import { Route as LoginRouteImport } from './routes/login';
import { Route as ServersRouteImport } from './routes/servers';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as SetupRouteImport } from './routes/setup';
import { Route as IncidentsIdRouteImport } from './routes/incidents_.$id';
import { Route as IncidentsAutofixRouteImport } from './routes/incidents_.autofix';
import { Route as Login2faRouteImport } from './routes/login_.2fa';
import { Route as LoginRecoveryRouteImport } from './routes/login_.recovery';
import { Route as ServersBillingRouteImport } from './routes/servers_.billing';
import { Route as ServersProvidersRouteImport } from './routes/servers_.providers';
import { Route as ServersRemnawaveRouteImport } from './routes/servers_.remnawave';
import { Route as SettingsIndexRouteImport } from './routes/settings.index';
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance';
import { Route as SettingsAssistantRouteImport } from './routes/settings.assistant';
import { Route as SettingsAutochecksRouteImport } from './routes/settings.autochecks';
import { Route as SettingsBackupsRouteImport } from './routes/settings.backups';
import { Route as SettingsIncidentsRouteImport } from './routes/settings.incidents';
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications';
import { Route as SettingsSecurityRouteImport } from './routes/settings.security';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any);
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any);
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any);
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any);
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any);
const IncidentsIdRoute = IncidentsIdRouteImport.update({
  id: '/incidents_/$id',
  path: '/incidents/$id',
  getParentRoute: () => rootRouteImport,
} as any);
const IncidentsAutofixRoute = IncidentsAutofixRouteImport.update({
  id: '/incidents_/autofix',
  path: '/incidents/autofix',
  getParentRoute: () => rootRouteImport,
} as any);
const Login2faRoute = Login2faRouteImport.update({
  id: '/login_/2fa',
  path: '/login/2fa',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRecoveryRoute = LoginRecoveryRouteImport.update({
  id: '/login_/recovery',
  path: '/login/recovery',
  getParentRoute: () => rootRouteImport,
} as any);
const ServersBillingRoute = ServersBillingRouteImport.update({
  id: '/servers_/billing',
  path: '/servers/billing',
  getParentRoute: () => rootRouteImport,
} as any);
const ServersProvidersRoute = ServersProvidersRouteImport.update({
  id: '/servers_/providers',
  path: '/servers/providers',
  getParentRoute: () => rootRouteImport,
} as any);
const ServersRemnawaveRoute = ServersRemnawaveRouteImport.update({
  id: '/servers_/remnawave',
  path: '/servers/remnawave',
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsAssistantRoute = SettingsAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsAutochecksRoute = SettingsAutochecksRouteImport.update({
  id: '/autochecks',
  path: '/autochecks',
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsBackupsRoute = SettingsBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsIncidentsRoute = SettingsIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/assistant': typeof AssistantRoute;
  '/audit': typeof AuditRoute;
  '/incidents': typeof IncidentsRoute;
  '/knowledge': typeof KnowledgeRoute;
  '/lock': typeof LockRoute;
  '/login': typeof LoginRoute;
  '/servers': typeof ServersRoute;
  '/settings': typeof SettingsRouteWithChildren;
  '/setup': typeof SetupRoute;
  '/incidents/$id': typeof IncidentsIdRoute;
  '/incidents/autofix': typeof IncidentsAutofixRoute;
  '/login/2fa': typeof Login2faRoute;
  '/login/recovery': typeof LoginRecoveryRoute;
  '/servers/billing': typeof ServersBillingRoute;
  '/servers/providers': typeof ServersProvidersRoute;
  '/servers/remnawave': typeof ServersRemnawaveRoute;
  '/settings/appearance': typeof SettingsAppearanceRoute;
  '/settings/assistant': typeof SettingsAssistantRoute;
  '/settings/autochecks': typeof SettingsAutochecksRoute;
  '/settings/backups': typeof SettingsBackupsRoute;
  '/settings/incidents': typeof SettingsIncidentsRoute;
  '/settings/notifications': typeof SettingsNotificationsRoute;
  '/settings/security': typeof SettingsSecurityRoute;
  '/settings/': typeof SettingsIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/assistant': typeof AssistantRoute;
  '/audit': typeof AuditRoute;
  '/incidents': typeof IncidentsRoute;
  '/knowledge': typeof KnowledgeRoute;
  '/lock': typeof LockRoute;
  '/login': typeof LoginRoute;
  '/servers': typeof ServersRoute;
  '/setup': typeof SetupRoute;
  '/incidents/$id': typeof IncidentsIdRoute;
  '/incidents/autofix': typeof IncidentsAutofixRoute;
  '/login/2fa': typeof Login2faRoute;
  '/login/recovery': typeof LoginRecoveryRoute;
  '/servers/billing': typeof ServersBillingRoute;
  '/servers/providers': typeof ServersProvidersRoute;
  '/servers/remnawave': typeof ServersRemnawaveRoute;
  '/settings/appearance': typeof SettingsAppearanceRoute;
  '/settings/assistant': typeof SettingsAssistantRoute;
  '/settings/autochecks': typeof SettingsAutochecksRoute;
  '/settings/backups': typeof SettingsBackupsRoute;
  '/settings/incidents': typeof SettingsIncidentsRoute;
  '/settings/notifications': typeof SettingsNotificationsRoute;
  '/settings/security': typeof SettingsSecurityRoute;
  '/settings': typeof SettingsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/assistant': typeof AssistantRoute;
  '/audit': typeof AuditRoute;
  '/incidents': typeof IncidentsRoute;
  '/knowledge': typeof KnowledgeRoute;
  '/lock': typeof LockRoute;
  '/login': typeof LoginRoute;
  '/servers': typeof ServersRoute;
  '/settings': typeof SettingsRouteWithChildren;
  '/setup': typeof SetupRoute;
  '/incidents_/$id': typeof IncidentsIdRoute;
  '/incidents_/autofix': typeof IncidentsAutofixRoute;
  '/login_/2fa': typeof Login2faRoute;
  '/login_/recovery': typeof LoginRecoveryRoute;
  '/servers_/billing': typeof ServersBillingRoute;
  '/servers_/providers': typeof ServersProvidersRoute;
  '/servers_/remnawave': typeof ServersRemnawaveRoute;
  '/settings/appearance': typeof SettingsAppearanceRoute;
  '/settings/assistant': typeof SettingsAssistantRoute;
  '/settings/autochecks': typeof SettingsAutochecksRoute;
  '/settings/backups': typeof SettingsBackupsRoute;
  '/settings/incidents': typeof SettingsIncidentsRoute;
  '/settings/notifications': typeof SettingsNotificationsRoute;
  '/settings/security': typeof SettingsSecurityRoute;
  '/settings/': typeof SettingsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/assistant'
    | '/audit'
    | '/incidents'
    | '/knowledge'
    | '/lock'
    | '/login'
    | '/servers'
    | '/settings'
    | '/setup'
    | '/incidents/$id'
    | '/incidents/autofix'
    | '/login/2fa'
    | '/login/recovery'
    | '/servers/billing'
    | '/servers/providers'
    | '/servers/remnawave'
    | '/settings/appearance'
    | '/settings/assistant'
    | '/settings/autochecks'
    | '/settings/backups'
    | '/settings/incidents'
    | '/settings/notifications'
    | '/settings/security'
    | '/settings/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/assistant'
    | '/audit'
    | '/incidents'
    | '/knowledge'
    | '/lock'
    | '/login'
    | '/servers'
    | '/setup'
    | '/incidents/$id'
    | '/incidents/autofix'
    | '/login/2fa'
    | '/login/recovery'
    | '/servers/billing'
    | '/servers/providers'
    | '/servers/remnawave'
    | '/settings/appearance'
    | '/settings/assistant'
    | '/settings/autochecks'
    | '/settings/backups'
    | '/settings/incidents'
    | '/settings/notifications'
    | '/settings/security'
    | '/settings';
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/audit'
    | '/incidents'
    | '/knowledge'
    | '/lock'
    | '/login'
    | '/servers'
    | '/settings'
    | '/setup'
    | '/incidents_/$id'
    | '/incidents_/autofix'
    | '/login_/2fa'
    | '/login_/recovery'
    | '/servers_/billing'
    | '/servers_/providers'
    | '/servers_/remnawave'
    | '/settings/appearance'
    | '/settings/assistant'
    | '/settings/autochecks'
    | '/settings/backups'
    | '/settings/incidents'
    | '/settings/notifications'
    | '/settings/security'
    | '/settings/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AssistantRoute: typeof AssistantRoute;
  AuditRoute: typeof AuditRoute;
  IncidentsRoute: typeof IncidentsRoute;
  KnowledgeRoute: typeof KnowledgeRoute;
  LockRoute: typeof LockRoute;
  LoginRoute: typeof LoginRoute;
  ServersRoute: typeof ServersRoute;
  SettingsRoute: typeof SettingsRouteWithChildren;
  SetupRoute: typeof SetupRoute;
  IncidentsIdRoute: typeof IncidentsIdRoute;
  IncidentsAutofixRoute: typeof IncidentsAutofixRoute;
  Login2faRoute: typeof Login2faRoute;
  LoginRecoveryRoute: typeof LoginRecoveryRoute;
  ServersBillingRoute: typeof ServersBillingRoute;
  ServersProvidersRoute: typeof ServersProvidersRoute;
  ServersRemnawaveRoute: typeof ServersRemnawaveRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/assistant': {
      id: '/assistant';
      path: '/assistant';
      fullPath: '/assistant';
      preLoaderRoute: typeof AssistantRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/audit': {
      id: '/audit';
      path: '/audit';
      fullPath: '/audit';
      preLoaderRoute: typeof AuditRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/incidents': {
      id: '/incidents';
      path: '/incidents';
      fullPath: '/incidents';
      preLoaderRoute: typeof IncidentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/knowledge': {
      id: '/knowledge';
      path: '/knowledge';
      fullPath: '/knowledge';
      preLoaderRoute: typeof KnowledgeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/lock': {
      id: '/lock';
      path: '/lock';
      fullPath: '/lock';
      preLoaderRoute: typeof LockRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/servers': {
      id: '/servers';
      path: '/servers';
      fullPath: '/servers';
      preLoaderRoute: typeof ServersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/setup': {
      id: '/setup';
      path: '/setup';
      fullPath: '/setup';
      preLoaderRoute: typeof SetupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/incidents_/$id': {
      id: '/incidents_/$id';
      path: '/incidents/$id';
      fullPath: '/incidents/$id';
      preLoaderRoute: typeof IncidentsIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/incidents_/autofix': {
      id: '/incidents_/autofix';
      path: '/incidents/autofix';
      fullPath: '/incidents/autofix';
      preLoaderRoute: typeof IncidentsAutofixRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login_/2fa': {
      id: '/login_/2fa';
      path: '/login/2fa';
      fullPath: '/login/2fa';
      preLoaderRoute: typeof Login2faRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login_/recovery': {
      id: '/login_/recovery';
      path: '/login/recovery';
      fullPath: '/login/recovery';
      preLoaderRoute: typeof LoginRecoveryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/servers_/billing': {
      id: '/servers_/billing';
      path: '/servers/billing';
      fullPath: '/servers/billing';
      preLoaderRoute: typeof ServersBillingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/servers_/providers': {
      id: '/servers_/providers';
      path: '/servers/providers';
      fullPath: '/servers/providers';
      preLoaderRoute: typeof ServersProvidersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/servers_/remnawave': {
      id: '/servers_/remnawave';
      path: '/servers/remnawave';
      fullPath: '/servers/remnawave';
      preLoaderRoute: typeof ServersRemnawaveRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/settings/': {
      id: '/settings/';
      path: '/';
      fullPath: '/settings/';
      preLoaderRoute: typeof SettingsIndexRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    '/settings/appearance': {
      id: '/settings/appearance';
      path: '/appearance';
      fullPath: '/settings/appearance';
      preLoaderRoute: typeof SettingsAppearanceRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    '/settings/assistant': {
      id: '/settings/assistant';
      path: '/assistant';
      fullPath: '/settings/assistant';
      preLoaderRoute: typeof SettingsAssistantRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    '/settings/autochecks': {
      id: '/settings/autochecks';
      path: '/autochecks';
      fullPath: '/settings/autochecks';
      preLoaderRoute: typeof SettingsAutochecksRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    '/settings/backups': {
      id: '/settings/backups';
      path: '/backups';
      fullPath: '/settings/backups';
      preLoaderRoute: typeof SettingsBackupsRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    '/settings/incidents': {
      id: '/settings/incidents';
      path: '/incidents';
      fullPath: '/settings/incidents';
      preLoaderRoute: typeof SettingsIncidentsRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    '/settings/notifications': {
      id: '/settings/notifications';
      path: '/notifications';
      fullPath: '/settings/notifications';
      preLoaderRoute: typeof SettingsNotificationsRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    '/settings/security': {
      id: '/settings/security';
      path: '/security';
      fullPath: '/settings/security';
      preLoaderRoute: typeof SettingsSecurityRouteImport;
      parentRoute: typeof SettingsRoute;
    };
  }
}

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute;
  SettingsAssistantRoute: typeof SettingsAssistantRoute;
  SettingsAutochecksRoute: typeof SettingsAutochecksRoute;
  SettingsBackupsRoute: typeof SettingsBackupsRoute;
  SettingsIncidentsRoute: typeof SettingsIncidentsRoute;
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute;
  SettingsSecurityRoute: typeof SettingsSecurityRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsAssistantRoute: SettingsAssistantRoute,
  SettingsAutochecksRoute: SettingsAutochecksRoute,
  SettingsBackupsRoute: SettingsBackupsRoute,
  SettingsIncidentsRoute: SettingsIncidentsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
};

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuditRoute: AuditRoute,
  IncidentsRoute: IncidentsRoute,
  KnowledgeRoute: KnowledgeRoute,
  LockRoute: LockRoute,
  LoginRoute: LoginRoute,
  ServersRoute: ServersRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
  IncidentsIdRoute: IncidentsIdRoute,
  IncidentsAutofixRoute: IncidentsAutofixRoute,
  Login2faRoute: Login2faRoute,
  LoginRecoveryRoute: LoginRecoveryRoute,
  ServersBillingRoute: ServersBillingRoute,
  ServersProvidersRoute: ServersProvidersRoute,
  ServersRemnawaveRoute: ServersRemnawaveRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
